### ISSUE TITLE
Scrape "About this item" section(4) not working

### ISSUE THREAD

**Issue by sudhanshu19102003** [sudhanshu19102003/ShopSense#1]
![Screenshot 2023-07-29 132212](https://github.com/sudhanshu19102003/ShopSense/assets/78022236/4e4d7eae-e2cb-4ee1-bda7-7aac932c9ea0)

**Comment by sudhanshu19102003** [comment]
![Screenshot 2023-07-29 132325](https://github.com/sudhanshu19102003/ShopSense/assets/78022236/0d120311-4f5e-439d-9948-cc82e506d979)

<h2> This should Scrape this part of the webside</h2>

**Comment by swax10** [comment]
Technical_Details issue (#1) solved
![111111](https://github.com/sudhanshu19102003/ShopSense/assets/110764543/1171d9b9-f3dd-4999-9540-40df24d14b9a)
